### ISSUE TITLE
problem with grunt license

### ISSUE THREAD

**Issue by seal-ss** [thenativeweb/tourism#27] opened 2015-02-23 10:20 UTC
Thanks for adding license check. I use the following `Gruntfile.js`:

``` javascript
'use strict';

var tourism = require('tourism');

module.exports = tourism({
  analyse: {
    server: [ '**/*.js', '!node_modules/**/*.js', '!coverage/**' ],
    options: {
      server: {
        language: 'es5'
      }
    }
  },
  licenses: [ 'MIT', 'BSD' ],
  test: {
    server: [ 'test/**/*.js' ]
  }
});
```

But after calling `grunt` a lot of error messages are shown:

``` bash
$ grunt
Running "eslint:server" (eslint) task


Running "mochacli:all" (mochacli) task


  0 passing (2ms)


Running "depcheck:files" (depcheck) task

Running "devUpdate:main" (devUpdate) task
Found 2 devDependencies to check for latest version
Found 2 dependencies to check for latest version
>> All packages are up to date

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?
...
Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?

Running "licensechecker" task
>> Local Npm module "grunt-license" not found. Is it installed?
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
...
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded
```

Do you have any hints?

**Comment by goloroden** [comment] 2015-02-23 19:24
Yes :-(

The problem is that tourism uses its own Grunt plugin module loading mechanism. This basically allows you not to have to specify each Grunt plugin inside of your application's `package.json`.

Now, `grunt-licensechecker` has a *peer* dependency on `grunt-license`. While installation and detection of it works for tourism itself, it apparently does not work when using tourism inside of a project :-/

So, for now this is a bug, and it must be fixed, but I need to find a solution first :-(

Anyway, thanks for pointing it out :-)

**Comment by goloroden** [comment] 2016-11-15 08:20
Since development of tourism is not continued any more, I'm going to close this one.

For the successor, see [roboter](https://github.com/thenativeweb/roboter).

**Closed by goloroden** 2016-11-15 08:20 UTC
